apiVersion: v1
kind: ServiceAccount
metadata:
  name: par-runner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: par-runner-role
rules:
  # apiextensions - CustomResourceDefinitions
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

  # apps - Deployments, DaemonSets, StatefulSets, ReplicaSets, ControllerRevisions
  - apiGroups: ["apps"]
    resources:
      - controllerrevisions
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

  # batch - Jobs, CronJobs
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

  # core - Pods, Services, ConfigMaps, Secrets, etc.
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - pods/exec
      - pods/log
      - podtemplates
      - replicationcontrollers
      - replicationcontrollers/scale
      - resourcequotas
      - serviceaccounts
      - services
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

  # custom resources - access to any custom objects
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: par-runner-binding
subjects:
  - kind: ServiceAccount
    name: datadog-par-private-action-runner
    namespace: default
roleRef:
  kind: ClusterRole
  name: par-runner-role
  apiGroup: rbac.authorization.k8s.io
