# First, create the datadog-secret with the folling command:
# kubectl create secret generic datadog-secret --from-literal api-key=$DD_API_KEY --from-literal app-key=$DD_APP_KEY

apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog-agent
  annotations:
    agent.datadoghq.com/private-action-runner-enabled: "true"
    agent.datadoghq.com/private-action-runner-configdata: |
      private_action_runner:
        enabled: true
        self_enroll: true
        actions_allowlist:
          - com.datadoghq.ddagent.testConnection
          - com.datadoghq.ddagent.logs.headFile
          - com.datadoghq.ddagent.logs.tailFile
          - com.datadoghq.ddagent.logs.listFiles
          - com.datadoghq.ddagent.logs.listProcessLogs
          - com.datadoghq.ddagent.shell.runShell
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    clusterName: kind-par-dev
    site: datad0g.com
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
  override:
    nodeAgent:
      image:
        name: registry.ddbuild.io/ci/datadog-agent/agent:v99464809-71f5ec5a-7-arm64
      volumes:
        - name: par-scripts
          secret:
            secretName: par-script-credentials
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: host-etc
          hostPath:
            path: /etc
            type: Directory
        - name: host-var
          hostPath:
            path: /var
            type: Directory
        - name: host-opt
          hostPath:
            path: /opt
            type: DirectoryOrCreate
        - name: host-home
          hostPath:
            path: /home
            type: DirectoryOrCreate
        - name: host-tmp
          hostPath:
            path: /tmp
            type: Directory
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
      containers:
        agent:
          env:
            - name: DD_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DD_KUBELET_TLS_VERIFY
              value: "false"
        private-action-runner:
          env:
            - name: DD_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: true
            - name: host-etc
              mountPath: /host/etc
              readOnly: true
            - name: host-var
              mountPath: /host/var
              readOnly: true
            - name: host-opt
              mountPath: /host/opt
              readOnly: true
            - name: host-home
              mountPath: /host/home
              readOnly: true
            - name: host-tmp
              mountPath: /host/tmp
              readOnly: true
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
    clusterAgent:
      image:
        name: docker.io/datadog/cluster-agent:7.76.0-rc.3
