# Grant the operator service account cluster-admin so it can create
# the ClusterRoles and ClusterRoleBindings required by the Datadog Agent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-operator-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: datadog-operator
    namespace: default
